---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "knative-operator.fullname" . }}-config-logging
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
data:
  _example: {{ .Values.configLogging.Example | toYaml | indent 1 }}