---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "knative-operator.fullname" . }}-operator-webhook-certs
  labels:
    app.kubernetes.io/component: operator-webhook
  {{- include "knative-operator.labels" . | nindent 4 }}