---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-operator.fullname" . }}-knative-operator
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.knativeOperator.serviceAccount.annotations | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "knative-operator.fullname" . }}-operator-webhook
  labels:
  {{- include "knative-operator.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.operatorWebhook.serviceAccount.annotations | nindent 4 }}